- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: true
  tasks:

    - name: Pull the latest Docker image
      command: docker pull mt2024013/scientific-calculator

    - name: Stop existing container (if running)
      command: docker stop calculator_container
      ignore_errors: yes

    - name: Remove old container (if exists)
      command: docker rm calculator_container
      ignore_errors: yes

    - name: Run new container in background
      command: docker run -d -it --name calculator_container mt2024013/scientific-calculator
